### ISSUE TITLE
What's the method of pseudo label calculation?

### ISSUE THREAD

**Issue by ytydt** [AndyJZhao/GraphText#1]
It seems that if you have a label of the center nodes, a.k.a. target nodes , there're no need for LLM to classify them again. So do you get the pseudo labels by GNNs, then use LLM to enhance the performance?

**Comment by AndyJZhao** [comment]
Thanks for the interest in our work. The pseudo-labels are obtained by label propagation, e.g. $A^2Y_L$ which does not guarantee correctness. LLM still need to judge whether the propagated labels are more useful or the neighborhood information is more useful.
